name: eShopOnWeb Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE-GROUP: rg-eshoponweb-eastus
  LOCATION: Central India
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 9272998d-dcde-4cfa-b573-faa8cf4007e7
  WEBAPP-NAME: devops-webapp-eastus-312412043

jobs:
  # Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v4

      # prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      # Build/Test/Publish the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      # upload the bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    # Add your deployment steps here
